name: Refresh Data

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm start